apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-server-deployment
  labels:
    app: email-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: email-server
  template:
    metadata:
      labels:
        app: email-server
    spec:
      volumes:
      - name: email-server-config
        configMap:
          name: backend-configmap
      containers:
      - name: email-server
        image: europe-west3-docker.pkg.dev/agora-jegyrendszer/jegyrendszer/email-server:1.2
        # imagePullPolicy: Always
        resources:
          limits:
            cpu: 200m
            memory: 2Gi
          requests:
            cpu: 200m
            memory: 1Gi
        ports:
        - containerPort: 5000
        envFrom:
        - secretRef:
            name: email-server-secretmap
        env:
        - name: CONFIGDIR
          value: "/etc/config"
        - name: FLASK_APP
          value: "main.py"
        volumeMounts:
        - name: email-server-config
          mountPath: /etc/config
---
apiVersion: v1
kind: Service
metadata:
  name: email-server-svc
spec:
  selector:
    app: email-server
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
---
apiVersion: v1
kind: Secret
metadata:
  name: email-server-secretmap
type: Opaque
data:
  PYPASS: bmJkY2VjZnp4Z2NibnpiZQo=